- hosts: all
  become: yes
  remote_user: ec2-user

  tasks:
    - name: Install NGINX and other packages
      yum:
        name:
          - vim
          - git
          - nginx
        state: present

    - name: Start and enable NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom HTML file
      copy:
        src: /home/ec2-user/index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0777'
